version: '3.8'

services:
  app:
    image: mcr.microsoft.com/devcontainers/dotnet:8.0
    command: sleep infinity
    depends_on:
      - sqlserver
    volumes:
      - ..:/app
    environment:
      - ConnectionStrings__DockerSql=Server=sqlserver,1433;Database=Todos;User Id=sa;Password=Password123;TrustServerCertificate=True;
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Password123
